/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AttendeeRouteImport } from './routes/attendee'
import { Route as ClientRouteImport } from './routes/client'
import { Route as DebugRouteImport } from './routes/debug'
import { Route as LoginRouteImport } from './routes/login'
import { Route as OnboardRouteImport } from './routes/onboard'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminGeofencesRouteImport } from './routes/admin/geofences'
import { Route as AdminLogsRouteImport } from './routes/admin/logs'
import { Route as AdminOrganizationRouteImport } from './routes/admin/organization'
import { Route as AdminProfileRouteImport } from './routes/admin/profile'
import { Route as AdminSettingsRouteImport } from './routes/admin/settings'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AttendeeDashboardRouteImport } from './routes/attendee/dashboard'
import { Route as AttendeeLogsRouteImport } from './routes/attendee/logs'
import { Route as AttendeeProfileRouteImport } from './routes/attendee/profile'
import { Route as ClientCategoriesRouteImport } from './routes/client/categories'
import { Route as ClientDashboardRouteImport } from './routes/client/dashboard'
import { Route as ClientGeofencesRouteImport } from './routes/client/geofences'
import { Route as ClientLogsRouteImport } from './routes/client/logs'
import { Route as ClientProfileRouteImport } from './routes/client/profile'
import { Route as ClientUsersRouteImport } from './routes/client/users'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AttendeeRoute = AttendeeRouteImport.update({
  id: '/attendee',
  path: '/attendee',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const DebugRoute = DebugRouteImport.update({
  id: '/debug',
  path: '/debug',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardRoute = OnboardRouteImport.update({
  id: '/onboard',
  path: '/onboard',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any)
const AdminGeofencesRoute = AdminGeofencesRouteImport.update({
  id: '/geofences',
  path: '/geofences',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLogsRoute = AdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AdminRoute,
} as any)
const AdminOrganizationRoute = AdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProfileRoute = AdminProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSettingsRoute = AdminSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AttendeeDashboardRoute = AttendeeDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AttendeeRoute,
} as any)
const AttendeeLogsRoute = AttendeeLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AttendeeRoute,
} as any)
const AttendeeProfileRoute = AttendeeProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AttendeeRoute,
} as any)
const ClientCategoriesRoute = ClientCategoriesRouteImport.update({
  id: '/categories',
  path: '/categories',
  getParentRoute: () => ClientRoute,
} as any)
const ClientDashboardRoute = ClientDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => ClientRoute,
} as any)
const ClientGeofencesRoute = ClientGeofencesRouteImport.update({
  id: '/geofences',
  path: '/geofences',
  getParentRoute: () => ClientRoute,
} as any)
const ClientLogsRoute = ClientLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => ClientRoute,
} as any)
const ClientProfileRoute = ClientProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ClientRoute,
} as any)
const ClientUsersRoute = ClientUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => ClientRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/attendee': typeof AttendeeRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/geofences': typeof AdminGeofencesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/attendee/dashboard': typeof AttendeeDashboardRoute
  '/attendee/logs': typeof AttendeeLogsRoute
  '/attendee/profile': typeof AttendeeProfileRoute
  '/client/categories': typeof ClientCategoriesRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/geofences': typeof ClientGeofencesRoute
  '/client/logs': typeof ClientLogsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/users': typeof ClientUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/attendee': typeof AttendeeRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/geofences': typeof AdminGeofencesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/attendee/dashboard': typeof AttendeeDashboardRoute
  '/attendee/logs': typeof AttendeeLogsRoute
  '/attendee/profile': typeof AttendeeProfileRoute
  '/client/categories': typeof ClientCategoriesRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/geofences': typeof ClientGeofencesRoute
  '/client/logs': typeof ClientLogsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/users': typeof ClientUsersRoute
  '/admin': typeof AdminIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/attendee': typeof AttendeeRouteWithChildren
  '/client': typeof ClientRouteWithChildren
  '/debug': typeof DebugRoute
  '/login': typeof LoginRoute
  '/onboard': typeof OnboardRoute
  '/register': typeof RegisterRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/geofences': typeof AdminGeofencesRoute
  '/admin/logs': typeof AdminLogsRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/profile': typeof AdminProfileRoute
  '/admin/settings': typeof AdminSettingsRoute
  '/admin/users': typeof AdminUsersRoute
  '/attendee/dashboard': typeof AttendeeDashboardRoute
  '/attendee/logs': typeof AttendeeLogsRoute
  '/attendee/profile': typeof AttendeeProfileRoute
  '/client/categories': typeof ClientCategoriesRoute
  '/client/dashboard': typeof ClientDashboardRoute
  '/client/geofences': typeof ClientGeofencesRoute
  '/client/logs': typeof ClientLogsRoute
  '/client/profile': typeof ClientProfileRoute
  '/client/users': typeof ClientUsersRoute
  '/admin/': typeof AdminIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/attendee'
    | '/client'
    | '/debug'
    | '/login'
    | '/onboard'
    | '/register'
    | '/admin/dashboard'
    | '/admin/geofences'
    | '/admin/logs'
    | '/admin/organization'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/attendee/dashboard'
    | '/attendee/logs'
    | '/attendee/profile'
    | '/client/categories'
    | '/client/dashboard'
    | '/client/geofences'
    | '/client/logs'
    | '/client/profile'
    | '/client/users'
    | '/admin/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/attendee'
    | '/client'
    | '/debug'
    | '/login'
    | '/onboard'
    | '/register'
    | '/admin/dashboard'
    | '/admin/geofences'
    | '/admin/logs'
    | '/admin/organization'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/attendee/dashboard'
    | '/attendee/logs'
    | '/attendee/profile'
    | '/client/categories'
    | '/client/dashboard'
    | '/client/geofences'
    | '/client/logs'
    | '/client/profile'
    | '/client/users'
    | '/admin'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/attendee'
    | '/client'
    | '/debug'
    | '/login'
    | '/onboard'
    | '/register'
    | '/admin/dashboard'
    | '/admin/geofences'
    | '/admin/logs'
    | '/admin/organization'
    | '/admin/profile'
    | '/admin/settings'
    | '/admin/users'
    | '/attendee/dashboard'
    | '/attendee/logs'
    | '/attendee/profile'
    | '/client/categories'
    | '/client/dashboard'
    | '/client/geofences'
    | '/client/logs'
    | '/client/profile'
    | '/client/users'
    | '/admin/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  AttendeeRoute: typeof AttendeeRouteWithChildren
  ClientRoute: typeof ClientRouteWithChildren
  DebugRoute: typeof DebugRoute
  LoginRoute: typeof LoginRoute
  OnboardRoute: typeof OnboardRoute
  RegisterRoute: typeof RegisterRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/attendee': {
      id: '/attendee'
      path: '/attendee'
      fullPath: '/attendee'
      preLoaderRoute: typeof AttendeeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/debug': {
      id: '/debug'
      path: '/debug'
      fullPath: '/debug'
      preLoaderRoute: typeof DebugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboard': {
      id: '/onboard'
      path: '/onboard'
      fullPath: '/onboard'
      preLoaderRoute: typeof OnboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/geofences': {
      id: '/admin/geofences'
      path: '/geofences'
      fullPath: '/admin/geofences'
      preLoaderRoute: typeof AdminGeofencesRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/logs': {
      id: '/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization': {
      id: '/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/profile': {
      id: '/admin/profile'
      path: '/profile'
      fullPath: '/admin/profile'
      preLoaderRoute: typeof AdminProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/settings': {
      id: '/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AdminSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/attendee/dashboard': {
      id: '/attendee/dashboard'
      path: '/dashboard'
      fullPath: '/attendee/dashboard'
      preLoaderRoute: typeof AttendeeDashboardRouteImport
      parentRoute: typeof AttendeeRoute
    }
    '/attendee/logs': {
      id: '/attendee/logs'
      path: '/logs'
      fullPath: '/attendee/logs'
      preLoaderRoute: typeof AttendeeLogsRouteImport
      parentRoute: typeof AttendeeRoute
    }
    '/attendee/profile': {
      id: '/attendee/profile'
      path: '/profile'
      fullPath: '/attendee/profile'
      preLoaderRoute: typeof AttendeeProfileRouteImport
      parentRoute: typeof AttendeeRoute
    }
    '/client/categories': {
      id: '/client/categories'
      path: '/categories'
      fullPath: '/client/categories'
      preLoaderRoute: typeof ClientCategoriesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/dashboard': {
      id: '/client/dashboard'
      path: '/dashboard'
      fullPath: '/client/dashboard'
      preLoaderRoute: typeof ClientDashboardRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/geofences': {
      id: '/client/geofences'
      path: '/geofences'
      fullPath: '/client/geofences'
      preLoaderRoute: typeof ClientGeofencesRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/logs': {
      id: '/client/logs'
      path: '/logs'
      fullPath: '/client/logs'
      preLoaderRoute: typeof ClientLogsRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/profile': {
      id: '/client/profile'
      path: '/profile'
      fullPath: '/client/profile'
      preLoaderRoute: typeof ClientProfileRouteImport
      parentRoute: typeof ClientRoute
    }
    '/client/users': {
      id: '/client/users'
      path: '/users'
      fullPath: '/client/users'
      preLoaderRoute: typeof ClientUsersRouteImport
      parentRoute: typeof ClientRoute
    }
  }
}

interface AdminRouteChildren {
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminGeofencesRoute: typeof AdminGeofencesRoute
  AdminLogsRoute: typeof AdminLogsRoute
  AdminOrganizationRoute: typeof AdminOrganizationRoute
  AdminProfileRoute: typeof AdminProfileRoute
  AdminSettingsRoute: typeof AdminSettingsRoute
  AdminUsersRoute: typeof AdminUsersRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminDashboardRoute: AdminDashboardRoute,
  AdminGeofencesRoute: AdminGeofencesRoute,
  AdminLogsRoute: AdminLogsRoute,
  AdminOrganizationRoute: AdminOrganizationRoute,
  AdminProfileRoute: AdminProfileRoute,
  AdminSettingsRoute: AdminSettingsRoute,
  AdminUsersRoute: AdminUsersRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface AttendeeRouteChildren {
  AttendeeDashboardRoute: typeof AttendeeDashboardRoute
  AttendeeLogsRoute: typeof AttendeeLogsRoute
  AttendeeProfileRoute: typeof AttendeeProfileRoute
}

const AttendeeRouteChildren: AttendeeRouteChildren = {
  AttendeeDashboardRoute: AttendeeDashboardRoute,
  AttendeeLogsRoute: AttendeeLogsRoute,
  AttendeeProfileRoute: AttendeeProfileRoute,
}

const AttendeeRouteWithChildren = AttendeeRoute._addFileChildren(
  AttendeeRouteChildren,
)

interface ClientRouteChildren {
  ClientCategoriesRoute: typeof ClientCategoriesRoute
  ClientDashboardRoute: typeof ClientDashboardRoute
  ClientGeofencesRoute: typeof ClientGeofencesRoute
  ClientLogsRoute: typeof ClientLogsRoute
  ClientProfileRoute: typeof ClientProfileRoute
  ClientUsersRoute: typeof ClientUsersRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientCategoriesRoute: ClientCategoriesRoute,
  ClientDashboardRoute: ClientDashboardRoute,
  ClientGeofencesRoute: ClientGeofencesRoute,
  ClientLogsRoute: ClientLogsRoute,
  ClientProfileRoute: ClientProfileRoute,
  ClientUsersRoute: ClientUsersRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  AttendeeRoute: AttendeeRouteWithChildren,
  ClientRoute: ClientRouteWithChildren,
  DebugRoute: DebugRoute,
  LoginRoute: LoginRoute,
  OnboardRoute: OnboardRoute,
  RegisterRoute: RegisterRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
